export * from './help';
export * from './ls';
export * from './cd';
export * from './pwd';
export * from './cat';
export * from './mkdir';
export * from './touch';
export * from './rm';
export * from './mv';
export * from './cp';
export * from './echo';
export * from './whoami';
export * from './hostname';
export * from './history';
export * from './tree';
export * from './find';
export * from './stat';
export * from './neofetch';
export * from './open';
export * from './mimi';
export * from './access';
export * from './clear';
export * from './uname';
export * from './motd';
export * from './about';
export * from './sudo';
export * from './matrix';
export * from './hash';
export * from './base64';
export * from './scan';
export * from './challenge';
export * from './achievements';
export * from './snake';
export * from './cyberTools';

// Import and register all commands
import { registerCommand } from '../commands';
import { helpCommand } from './help';
import { lsCommand } from './ls';
import { cdCommand } from './cd';
import { pwdCommand } from './pwd';
import { catCommand } from './cat';
import { mkdirCommand } from './mkdir';
import { touchCommand } from './touch';
import { rmCommand } from './rm';
import { mvCommand } from './mv';
import { cpCommand } from './cp';
import { echoCommand } from './echo';
import { whoamiCommand } from './whoami';
import { hostnameCommand } from './hostname';
import { historyCommand } from './history';
import { treeCommand } from './tree';
import { findCommand } from './find';
import { statCommand } from './stat';
import { neofetchCommand, systeminfoCommand } from './neofetch';
import { openCommand } from './open';
import { mimiCommand } from './mimi';
import { accessCommand } from './access';
import { clearCommand, clsCommand } from './clear';
import { unameCommand } from './uname';
import { motdCommand } from './motd';
import { aboutCommand } from './about';
import { sudoCommand } from './sudo';
import { matrixCommand } from './matrix';
import { hashCommand } from './hash';
import { base64Command } from './base64';
import { scanCommand, nmapCommand } from './scan';
import { challengeCommand } from './challenge';
import { achievementsCommand, badgesCommand } from './achievements';
import { snakeCommand } from './snake';
import { packetmonCommand, wifiscanCommand, seclogCommand } from './cyberTools';

// Register all commands
registerCommand(helpCommand);
registerCommand(lsCommand);
registerCommand(cdCommand);
registerCommand(pwdCommand);
registerCommand(catCommand);
registerCommand(mkdirCommand);
registerCommand(touchCommand);
registerCommand(rmCommand);
registerCommand(mvCommand);
registerCommand(cpCommand);
registerCommand(echoCommand);
registerCommand(whoamiCommand);
registerCommand(hostnameCommand);
registerCommand(historyCommand);
registerCommand(treeCommand);
registerCommand(findCommand);
registerCommand(statCommand);
registerCommand(neofetchCommand);
registerCommand(systeminfoCommand);
registerCommand(openCommand);
registerCommand(mimiCommand);
registerCommand(accessCommand);
registerCommand(clearCommand);
registerCommand(clsCommand);
registerCommand(unameCommand);
registerCommand(motdCommand);
registerCommand(aboutCommand);
registerCommand(sudoCommand);
registerCommand(matrixCommand);
registerCommand(hashCommand);
registerCommand(base64Command);
registerCommand(scanCommand);
registerCommand(nmapCommand);
registerCommand(challengeCommand);
registerCommand(achievementsCommand);
registerCommand(badgesCommand);
registerCommand(snakeCommand);
registerCommand(packetmonCommand);
registerCommand(wifiscanCommand);
registerCommand(seclogCommand);