export * from './help';
export * from './ls';
export * from './cd';
export * from './pwd';
export * from './cat';
export * from './mkdir';
export * from './touch';
export * from './rm';
export * from './mv';
export * from './cp';
export * from './echo';
export * from './whoami';
export * from './hostname';
export * from './history';
export * from './tree';
export * from './find';
export * from './stat';
export * from './neofetch';
export * from './open';
export * from './mimi';
export * from './access';

// Import and register all commands
import { registerCommand } from '../commands';
import { helpCommand } from './help';
import { lsCommand } from './ls';
import { cdCommand } from './cd';
import { pwdCommand } from './pwd';
import { catCommand } from './cat';
import { mkdirCommand } from './mkdir';
import { touchCommand } from './touch';
import { rmCommand } from './rm';
import { mvCommand } from './mv';
import { cpCommand } from './cp';
import { echoCommand } from './echo';
import { whoamiCommand } from './whoami';
import { hostnameCommand } from './hostname';
import { historyCommand } from './history';
import { treeCommand } from './tree';
import { findCommand } from './find';
import { statCommand } from './stat';
import { neofetchCommand } from './neofetch';
import { openCommand } from './open';
import { mimiCommand } from './mimi';
import { accessCommand } from './access';

// Register all commands
registerCommand(helpCommand);
registerCommand(lsCommand);
registerCommand(cdCommand);
registerCommand(pwdCommand);
registerCommand(catCommand);
registerCommand(mkdirCommand);
registerCommand(touchCommand);
registerCommand(rmCommand);
registerCommand(mvCommand);
registerCommand(cpCommand);
registerCommand(echoCommand);
registerCommand(whoamiCommand);
registerCommand(hostnameCommand);
registerCommand(historyCommand);
registerCommand(treeCommand);
registerCommand(findCommand);
registerCommand(statCommand);
registerCommand(neofetchCommand);
registerCommand(openCommand);
registerCommand(mimiCommand);
registerCommand(accessCommand);